meta:
  environment: general-sensu-monitors-warden

  stemcell:
    name: bosh-warden-boshlite-ubuntu
    version: latest

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
  - name: plugins
    instances: 1
    networks:
      - name: general_sensu_monitors1
        static_ips: ~

compilation:
  cloud_properties:
    name: random

resource_pools:
  - name: small_z1
    cloud_properties:
      name: random

networks:
- name: general_sensu_monitors1
  # Assumes up to 5 VMs, including 1 static and 4 dynamic.
  # Plus 5 (double the size) unused IPs, due to BOSH bug/quirk.
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.9.0/30
    reserved:
    - 10.244.9.1
    static:
    - 10.244.9.2

  - cloud_properties:
      name: random
    range: 10.244.9.4/30
    reserved:
    - 10.244.9.5
    static: []
  - cloud_properties:
      name: random
    range: 10.244.9.8/30
    reserved:
    - 10.244.9.9
    static: []
  - cloud_properties:
      name: random
    range: 10.244.9.12/30
    reserved:
    - 10.244.9.13
    static: []
  - cloud_properties:
      name: random
    range: 10.244.9.16/30
    reserved:
    - 10.244.9.17
    static: []

  # Bonus double-sized network required due to BOSH oddity
  - cloud_properties:
      name: random
    range: 10.244.9.20/30
    reserved:
    - 10.244.9.21
    static: []
  - cloud_properties:
      name: random
    range: 10.244.9.24/30
    reserved:
    - 10.244.9.25
    static: []
  - cloud_properties:
      name: random
    range: 10.244.9.28/30
    reserved:
    - 10.244.9.29
    static: []
  - cloud_properties:
      name: random
    range: 10.244.9.32/30
    reserved:
    - 10.244.9.33
    static: []
  - cloud_properties:
      name: random
    range: 10.244.9.36/30
    reserved:
    - 10.244.9.37
    static: []
