meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: general_sensu_monitors_leader_z1
    template: general-sensu-monitors
    instances: 0
    resource_pool: small_z1
    networks: (( merge ))
    persistent_disk: 0
    properties: {}
  - name: general_sensu_monitors_z1
    template: general-sensu-monitors
    instances: 0
    resource_pool: small_z1
    networks: (( merge ))
    persistent_disk: 0
    update:
      canaries: 10
    properties:
      general_sensu_monitors:
        leader_address: (( merge ))

networks: (( merge ))

properties: {}
